### PR TITLE
Fix broken menu on mobile layout

### PR DESCRIPTION
**Pull request by arcristo**
On small screens the menu is collapsing just after being shown.

### CODE REVIEW

**Comment by froschdesign** [comment]
@arcristo 
LGTM! 👍 

Btw. I'm working on a new layout: #34

**Comment by arcristo** [comment]
@froschdesign Good to know!
I'll create a branch to test it.

**Comment by froschdesign** [comment]
@arcristo 
I would include your fix in #34.

**Comment by weierophinney** [comment]
Thanks, @arcristo! Merged, and as new builds for components occur, they will pick up the changes.

**Pull request merged**
